<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ ucfirst(str_replace('-', ' ', $reportType)) }} Report - {{ $dateFrom }} to {{ $dateTo }}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body {
            print-color-adjust: exact;
            -webkit-print-color-adjust: exact;
        }

        .page-break {
            page-break-after: always;
        }

        /* Ensure colors are rendered properly */
        * {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
        }
    </style>
</head>

<body class="bg-white">

    <!-- Report Content -->
    <div class="max-w-7xl mx-auto p-8">

        <!-- Report Header -->
        <div class="text-center mb-8 pb-6 border-b-2 border-gray-300">
            <h1 class="text-3xl font-bold text-gray-800 mb-2">
                {{ config('app.name', 'Denture Lab') }}
            </h1>
            <h2 class="text-xl font-semibold text-gray-700 mb-1">
                {{ ucfirst(str_replace('-', ' ', $reportType)) }} Report
            </h2>
            <p class="text-gray-600">
                Period: {{ \Carbon\Carbon::parse($dateFrom)->format('M d, Y') }} - {{
                \Carbon\Carbon::parse($dateTo)->format('M d, Y') }}
            </p>
            <p class="text-sm text-gray-500 mt-2">
                Generated on: {{ now()->format('M d, Y h:i A') }}
            </p>
        </div>

        <!-- Report Data -->
        @if($reportType === 'overview')
        @include('admin.reports.partials.overview', ['data' => $data])
        @elseif($reportType === 'case-orders')
        @include('admin.reports.partials.case-orders', ['data' => $data])
        @elseif($reportType === 'revenue')
        @include('admin.reports.partials.revenue', ['data' => $data])
        @elseif($reportType === 'materials')
        @include('admin.reports.partials.materials', ['data' => $data])
        @elseif($reportType === 'clinic-performance')
        @include('admin.reports.partials.clinic-performance', ['data' => $data])
        @elseif($reportType === 'technician-performance')
        @include('admin.reports.partials.technician-performance', ['data' => $data])
        @elseif($reportType === 'delivery-performance')
        @include('admin.reports.partials.delivery-performance', ['data' => $data])
        @endif

        <!-- Report Footer -->
        <div class="mt-12 pt-6 border-t-2 border-gray-300 text-center text-sm text-gray-600">
            <p>This is an official report generated by {{ config('app.name', 'Denture Lab') }}</p>
            <p class="mt-1">For inquiries, please contact the administration office.</p>
        </div>
    </div>

</body>

</html>